neithernut/git-dit

README.md

From here:
https://news.ycombinator.com/item?id=13732598
https://www.reddit.com/r/git/comments/5w55pp/gitdit_decentralized_issue_tracking_for_git/
As suggested.

Add post from reddit/hackernews in README

---

README.md
doc/README.md
doc/caveats.md
doc/datamodel.md
doc/issues.md
doc/use-cases.md

Add documentation of the data model

---

README.md
lib/Cargo.toml
lib/LICENSE
lib/README.md
lib/src/repository.rs

This is the tracking-PR for the library implementation.
I would model this as extension to the `git2::Repository` type. Further, I would model each shell script into one function on `Repository`.
I would like to hear your opinion before digging further into this.

Add repository module

---

lib/Cargo.toml
lib/src/error.rs
lib/src/first_parent_iter.rs
lib/src/lib.rs
lib/src/repository.rs

Introducing the error module and also minify the iterator implementation.

Patches for: Add preliminary implementation of find_tree_init_hash

---

Cargo.toml
lib/Cargo.toml
lib/src/error.rs
lib/src/first_parent_iter.rs
lib/src/lib.rs
lib/src/repository.rs
src/cli.yaml
src/error.rs
src/main.rs

Add preliminary implementation of find_tree_init_hash

---

lib/src/error.rs
lib/src/iter.rs
lib/src/lib.rs
lib/src/repository.rs
src/main.rs

Patches for: add get issue tree init hashes

---

src/main.rs

Add a macro which hopefully safes us a few lines of code. I'm happy to change the name if someone comes up with a better alternative.

Add a macro for early returns in subcommands

---

lib/src/iter.rs

Add an iterator to remove right-trailing whitespace from lines

---

lib/src/iter.rs

Add iterator type for removing comments

---

src/cli.yaml
src/main.rs

Luckily, the diff turns out to be smaller than expected.
Resolves #54.

Order subcommands in various places

---

lib/src/first_parent_iter.rs
lib/src/iter.rs
lib/src/message/mod.rs
lib/src/message/trailer.rs

This PR introduces a few additions and changes to the library, preparing #45.

Library additions and changes

---

src/main.rs

Fix typo in subcommand implementation sectioning

---

src/error.rs
src/programs.rs

Reimplement the programs module

---

src/main.rs
src/util.rs
src/write.rs

While working on `git dit reply`, a few changes emerged which have some influence on the implementation of `git dit new`.
In preparation of #70.

Git-dit-new refactor

---

src/logger.rs
src/main.rs

Add a basic logger and wire it up, so we actually see the errors we are reporting.

Enable logging

---

lib/src/lib.rs
src/callbacks.rs
src/error.rs
src/main.rs

Make "unused" warnings go away.

Clean unused

---

lib/src/first_parent_iter.rs
lib/src/iter.rs
lib/src/lib.rs
lib/src/message/line.rs
lib/src/message/mod.rs
lib/src/message/quoted.rs
lib/src/message/trailer.rs
lib/src/remote.rs
lib/src/repository.rs

In this PR, I add missing documentation to stuff in the library.
Resolves #76.

Add more documentation to library

---

lib/src/issue.rs
lib/src/iter.rs
lib/src/lib.rs
lib/src/repository.rs
src/main.rs

Add a dedicated type for issues

---

src/abort.rs
src/main.rs

We have a lot of ugly stuff in the binary, just for the sake of error handling. This PR aims to make this less painful.

Simplify error handling in the binary

---

lib/src/issue.rs
src/cli.yaml
src/error.rs
src/main.rs
src/util.rs

Parsing issues is a task which is performed in many subcommands. In most cases, the issue even is a required parameter. This PR introduces a function for parsing an issue from the command line.

Consolidate issue parsing in the binary

---

lib/src/iter.rs
lib/src/message/mod.rs
lib/src/message/trailer.rs
lib/src/repository.rs
src/callbacks.rs
src/logger.rs
src/main.rs
src/msgtree.rs
src/programs.rs
src/util.rs
src/write.rs

In some places, we import a specific data structure and use it in only one or two places. This PR targets those imports. Suggestions are welcome.

Clean imports

---

CHANGELOG.md
Cargo.toml
git-dit.1.md
lib/Cargo.toml
src/cli.yaml

Release preparations

---

doc/datamodel.md
git-dit.1.md
mkmanpage.rs

Improvements of the documentation

---

.gitignore
.travis.yml
lib/src/issue.rs
lib/src/lib.rs
lib/src/message/line.rs
lib/src/message/line_processor.rs
lib/src/message/mod.rs
lib/src/message/trailer.rs
lib/src/repository.rs
lib/src/test_utils.rs

Add various tests for the library

---

src/main.rs

The current implementation of the "list" subcommand is still based
solely on initial messages rather than on the `Issue` datatype. While
the initial message of an issue provided all information required for
the previous display, it may not provide sufficient data for future
sorting and filtering functionality.

Itreate over Issues rather than commits in "list" subcomand

---

lib/src/message/accumulation.rs
lib/src/message/metadata.rs
lib/src/message/mod.rs

We currently offer both tools for writing and accumulating metadata in the library. However, we lack some specification of metadata which we expect for issues.

Metadata specification

---

git-dit.1.md
lib/src/error.rs
lib/src/gc.rs
lib/src/iter.rs
lib/src/lib.rs
lib/src/repository.rs
lib/src/utils.rs
src/cli.yaml
src/main.rs

This PR introduces garbage collection facilities.

Collection of old references

---

src/cli.yaml
src/error.rs
src/filters.rs
src/main.rs

Introduce issue filtering functionality to the `git-dit` program. The functionality will be provided for the "list" subcommand.

Issue filtering

---

src/main.rs

The tag subcommand required a local head reference to be present for
operation. If no reference was present, the subcommand would produce an
error. This behavior was chosen because we did lack a selection
mechanism for remote heads. However, such a mechanism was recently
introduced.
This patch makes the "tag" subcommand use the remote priorization
mechanism for selecting a head reference.

Make git-dit-tag work without local head being present

---

git-dit.1.md

Add some additional bits and pieces to the manpage.

Manpage improvements

---

lib/src/README.md
lib/src/lib.rs
lib/src/trailer/filter.rs
src/README.md

This PR introduces some additional improvements to the documentation, including some architecture documentation.

Doc improvements

---

src/system/programs.rs

Compiled and tested. Works.
The commit message describes the problem and how it was fixed.
Closes #116

Implement string-splitting for multi-word configurations

---

CHANGELOG.md
Cargo.toml
README.md
git-dit.1.md
lib/Cargo.toml
src/cli.yaml

The release is scheduled for September the 15th.

Preparations for the 0.4.0 release

---

src/cli.yaml

Clearify documentation of metadata in "new" command
