neithernut/git-dit

- src/cli.yaml
- src/main.rs
This is my initial PR for porting the commandline to Rust.
This PR also introduces a `default.nix` file - if you think we shouldn't put these things in the repository, I'll happily remove it from my PR (and put an entry into `.gitignore` for it).
Please review the `cli.yml` carefully - there might be entries where the helptext/abouttext can be improved, and even more important: There might be entries where we can be more specific.
I did not yet extensively care about [the following configurations](https://docs.rs/clap/2.20.5/clap/struct.App.html):
* `before_help`
* `after_help`
* `requires`
* `conflicts_with`
* `settings`
* `group` / `groups`
* `display_order`
There is also no autocomplete-generating included in this PR.
> clap setup

- lib/src/repository.rs
This will be of use for retrieving all messages belonging for an issue,
e.g. for showing them all or performing garbage collection on refs.
Resolves #36.
> Add function for retrieving all leaf refs of an issue

- lib/src/message/line.rs
- lib/src/message/mod.rs
- lib/src/message/trailer.rs
This PR generalizes `Lines` and `Trailers` and makes them accessible via `LineIteratorExt`, rounding up the interface.
> Make Lines and Trailers accessible via the LineIteratorExt

- lib/src/iter.rs
- lib/src/message/mod.rs
This PR adds an extension trait for `git2::Commit`s, providing convenient access to some functionality. For this purpose, the `LineIteratorExt` is generalized, continuing the efforts of #57.
> Add an extension trait for commits

- lib/src/error.rs
- lib/src/message/line.rs
- lib/src/message/mod.rs
- lib/src/message/trailer.rs
This PR introduces some new interfaces to the `message` module of the library and refactors a few things on the way. In preparation for #67.
> Additions to the message module

- src/util.rs
`with_file_name()` didn't work as expected, resulting in an
`COMMIT_EDITMSG` file in the wrong directory. This commit replaces this
function with a `join()`, which always appends the file name to the
path.
> Fix commitmsg_edit_path()

- src/abort.rs
- src/main.rs
- src/util.rs
This PR introduces a small utility for simplifying the handling of `Iterator<Result>` types.
> Aborting iterator

- src/cli.yaml
- src/main.rs
There are multiple issues with the `src/cli.yaml`. Some settings are wrong, so are some strings in the source. We should have checked them earlier. This PR is intended for cleaning up the mess that we shouldn't have produced in the first place.
Most notably, the `multiple` setting for options appears to make clap account any argument following the option, until the next one starting with a dash `-`, to the option, even if a required parameter is to be expected. As a work-around, one can insert a `--`, but the behaviour is not what one wants and confusing to users, imo.
> Fix command line

- src/main.rs
If we don't catch empty subcommands, we end up with
`handle_unknown_subcommand()` trying to invoke a program named
`git-dit-`. This, in turn, results in a "No such file or directory"
error, which is not especially useful for the user.
This PR solves the issue. Empty subcommands are handled by printing
the usage to stderr.
> Catch empty subcommands

- .travis.yml
The reason for this is that some distributions are rather old for shipping updates here and (as far as I know by now) we can compile this with old versions.
If something breaks in an old version, we can fix is before the PR lands, as far as it is not too complicated to fix. Of course, the current version(s) of the rust compiler are prefered, but in most situations fixing the codebase for older versions won't hurt that much and the benefits are clearly more important than the draw-backs.
---
But before everything we should see whether this succeeds.
> Enable old rustc versions on travis

- .travis.yml
- Cargo.toml
- Makefile
- README.md
- mkmanpage.rs
This PR makes Cargo build the man page for us. The installation is, however, not performed. Since the `Makefile` was only introduced in order to build the man page, it was removed.
Resolves #92 and #93.
> Make Cargo build the manpage

- .travis.yml
- mkmanpage.rs
The problem is that I don't want to install pandoc for development... and we cannot expect the casual hacker to do this, either.
So we make this dependend on a env variable. At least this is what I propose.
> Execute buildscript only if desired

- lib/src/error.rs
- lib/src/issue.rs
- lib/src/repository.rs
- src/main.rs
`repository::RepositoryExt::create_message()` is a function doing to some extent two different things, dependent on the `issue` parameter. That parameter still is an `Oid` despite the new `Issue` type (well, I simply forgot about it). In this PR, we rethink the `create_message()` interface.
I'd like to replace `create_message()` completely. However, I'm not yet sure with what to replace it. Suggestions are welcome.
> Rethink message creation

- .travis.yml
Apparently, some dependencies don't care about old rust-versions. Hence,
supporting those old versions doesn't make sense.
> Don't make the CI build for old rust-vresions

- lib/src/issue.rs
- lib/src/repository.rs
- src/main.rs
This PR aims at streamlining and redefining the methods for retrieval of issue references.
It contains breaking changes.
Block #117.
> Redefine retrieval of issue references 

- Cargo.toml
- lib/Cargo.toml
Add missing crate meta information.
Because of this we cannot publish 0.2.0 and 0.2.1 on crates.io.
> Add missing metadata

- git-dit.1.md
- lib/src/issue.rs
- src/cli.yaml
- src/main.rs
Authors of git server hooks (e.g. `update` hooks) may want to determine
of what type a given dit reference and whether it is a dit reference at
all.
> Determination of dit reference type

- lib/src/issue.rs
For some of the functions for the `Issue` type, we missed annotating the
return types with an explicit lifetime. This resulted in the default
lifetime assigned through lifetime elision. Those were far too strict
since the result's lifetime was those of the `Issue` rather then that of
the underlying `git2::Repository`.
Blocks #117.
> Improve issue lifetimes

- git-dit.1.md
- src/main.rs
- src/reference.rs
- src/util.rs
Currently, all references available for an issue are treated equally in some regards. For example, when querying the metadata, the next best head-reference is used. This behaviour is not optimal, especially in the light of multiple remotes and upcoming functionality.
> Remote priorization

- src/main.rs
We currently open the repository in the main function. This has the serious drawback that `git-dit` will look for a repository and abort on failure even if the subcommand invoked does not require a repository. Such subcommands include "check-message".
> Open the repository in the individual subcommands

- git-dit.1.md
- src/reference.rs
- src/util.rs
On second thought, it doesn't make much sense to automatically include remotes which are not prioritized by the user in the selection of references.
This PR changes the behavior accordingly. Instead, we allow for a special entry "*", which accepts any remote.
Blocks #134.
> Redefine remote prioritization

- lib/src/error.rs
- lib/src/issue.rs
- lib/src/iter.rs
- lib/src/repository.rs
- src/main.rs
Currently, we offer multiple iterators for iterating over messages. Sadly, most of those are isolated from each other. Additionally, we often provide only a `Revwalk` for general purpose usage when the goal is to iterate over messages.
> Consolidate message iteration

- git-dit.1.md
- lib/src/gc.rs
- lib/src/issue.rs
- lib/src/repository.rs
- src/cli.yaml
- src/main.rs
- src/util.rs
Some actions which may be performed on an issue repository requires local references to be present. E.g. transferring issues between two remotes involves pushing the references to the target remote. However, only local references can be pushed. A solution would be to mirror the references from the source as local references for pushing.
This PR implements a subcommand for mirroring refs.
> Subcommand for mirroring references

- lib/src/gc.rs
If remote references are considered during garbage collection, those
references should serve as starting points for the collection. We
erroneously added local references to the list of references (once
again) to be considered for collection instead. This resulted in leaves
not being collected when they should be.
This patch resolves the bug by pushing the remote references to the
correct revwalk.
> Fix garbage collection of leaves considering remote refs

- git-dit.1.md
The indentation results in the descriptions being incorrectly recognized
as code snippets.
> Remove indentation from subcommand description in manpage

- lib/src/issue.rs
- lib/src/repository.rs
- lib/src/utils.rs
- src/main.rs
- src/util.rs
`RepositoryExt::issues()` and `RepositoryExt::issues_with_prefix()` both
return an iterator over issues. In both cases, the issues are not
guaranteed to be unique and with the current implementation, an issue
may well be reported twice.
We implicitly assumed that issues would be reported only once. This lead
to `git-dit-list` reporting an issue twice if both a remote and a local
head reference exist for that issue. `git-dit-gc` would try to remove a
reference twice and hence display an error.
We could fix the behavior in places where we made the assumption.
However, when querying a list of issues it is sensible to assume that
the list would contain unique issues. This patch-set therefore aims at
changing the aforementioned query functions of `RepositoryExt`, making
each of them return a …
> Return set of unique issues from RepositoryExt functions

- examples/hooks/update
Server administrators may use the hook or parts of for dit-repositories
on their servers.
> Add an example update hook for realizing a dit-only policy

- src/cli.yaml
The option conflicts with the global "help" option.
Even worse, users may accidentally trigger removal of references when
trying to read the help-message.
> Remove ambiguous short option "h" from "gc" subcommand

- lib/src/issue.rs
- lib/src/repository.rs
Some existing and future functions of `Issue` operate on the initial message of the issue. If we store only the `Issue`s id, we have to retrieve the commit on multiple occasions, e.g. we have a potential for a lot of overhead.
Ideally, we would store the initial message as a `git2::Commit`. However, this is not practical due to some drawbacks of the interface. Storing an `Object` on the other hand provides at least some caching as well as other benefits.
> Redefine internals of Issue

- src/main.rs
With git2-0.6.7, the signature of the `References::names` changed (see alexcrichton/git2-rs#245). The function now takes a mutable reference and imposes an additional lifetime constraint on the returned iterator. The latter can not out-life the `References` struct any more. This lead to compilation failures.
The problem is resolved by pre-collecting all names as `String`s within a closure.
> Pre-collect names of local References in push_impl

- Cargo.toml
- lib/src/iter.rs
- lib/src/trailer/accumulation.rs
- lib/src/trailer/filter.rs
- lib/src/trailer/mod.rs
- src/error.rs
- src/filters.rs
- src/main.rs
Filtering issues based on metadata should be a relatively common task in applications associated with git-dit, including web-viewers and of course the `git-dit` binary. It therefore makes sense to provide some functionality associated with filtering in the library.
> Add issue filtering as a library feature

- lib/src/lib.rs
- src/display/formatter.rs
- src/display/message.rs
- src/display/mod.rs
- src/main.rs
Currently, the formatting of messages is hard-coded, for example for the "show" subcommand. This is not flexible regarding configurability via command line options. In particular, it does not allow a user defined formatting.
> Flexible message formatting

- src/error.rs
- src/gitext/callbacks.rs
- src/system/abort.rs
- src/system/logger.rs
- src/util.rs
It doesn't make so much sense to have it in the logger module since it doesn't depend on the specific logger implementation. Additionally, it enables a more strict dependency policy.
> Move the LoggableError type to the error module

- src/main.rs
- src/system/write.rs
We often create line iterators for writing via multiple steps. Currently, those iterators are bound to a name for readability, just to be passed to `WriteExt::consume_lines()`.
Implementing a `write_lines()` function on line iterators instead improves usability in conjunction with chaining, since the stream is usually retrieved more easily.
> Implement line writing on line iterators rather than streams

- src/cli.yaml
- src/error.rs
- src/main.rs
- src/util.rs
git commit` allows setting the author and date of a commit via command line parameters. This PR introduces a similar interface for the "create-message", "new" and "reply" subcommands. The new interface may be used for scripting, e.g. for implementing a mail-to-message bridge.
> Enable alternative author and date via cli parameters

- lib/src/message/line_processor.rs
- lib/src/message/mod.rs
In the library, we provide line oriented processing of text, e.g. messages.
Various processing may yield iterators with blank lines at the beginning or at the end of messages. While the former is relatively easy to filter out using `Iterator::skip_while()`, the latter is not as easy to avoid using rust standard tools.
In the library, we currently avoid the problem by removing trailing whitespace from strings, which are collected from lines anyway. However, library users may still be interested in a tool for removing trailing blank lines.
This patch-set introduces an iterator adapter for performing this task.
> Removal of trailing blank lines

- src/display/formatter.rs
- src/display/message.rs
- src/main.rs
For users, it may be important or at least interesting to know which is the head message when viewing an issue using `git dit show`. This patch-set adds such a marker.
> Add "head" marker to head message in show subcommand

- CHANGELOG.md
- lib/src/iter.rs
- lib/src/trailer/spec.rs
Commit message of the first patch:
---
This patch removes one level of generic by transforming it to an
associated type.
This improves usability of the traits because of fewer generics.
Also, generic output values are problematic because every function which
wants to be generic over the trait has also to be generic over the
generic return type of the functions of the trait (see rust
documentation on associated types).
This patch improves this.
---
I bet there are more places where this can be beautified.
> Remove generic type parameters in traits by using associated type

- src/display/message.rs
- src/display/msgtree.rs
Small fixes for removing compiler warnings from the compile output.
The second change might be redone by removing the enum variants, I'm not sure on that one.
> Fix warnings

- lib/src/utils.rs
While it is required for `ResultIterExt::collect_result_into()`, we do not need `Default` for `collect_result_into()`. The target already exists.
The requirement was likely introduced because of C&P.
> Do not require Default for collect_result_into() target

- lib/src/gc.rs
- lib/src/iter.rs
- lib/src/repository.rs
- src/main.rs
This is somewhat related to #174.
This patch-set decouples the collection of references for different issues. Leaves referenced by refs of another issue will no longer be collected. Issues are no longer supplied up-front via `CollectableRefs::new()` but are fed into `CollectableRefs::into_refs()` and `CollectableRefs::into_collector()`. However, users are discouraged from using those functions now. Instead, we introduces a new function `CollectableRefs::for_issue()` which allows collecting references for a single issue without mutating or consuming the `CollectableRefs`. It enables more direct updates, e.g. when using a `FlatMap` iterator.
> Refactor the GC code

- src/cli.yaml
- src/main.rs
This patch-set introduces multiple enhancements to the `git dit gc` subcommand. The main goal is to enable faster/more "responsive" collection.
It also enables collection for a subset of issues. This functionality may be used in server-side hooks, greatly enhancing the performance.
Resolves #174.
> Enhance the gc subcommand

- Cargo.toml
- src/main.rs
- src/system/write.rs
- src/util.rs
Instead of adding boilerplate code each time we use the pager, add a function to the `LinesExt` which handles paged output. The new function handles both waiting for the pager to be closed and TTY detection.
Superseeds #165.
> Pager via LinesExt

- src/cli.yaml
Apparently, it was not clear enough that the subcommand accepts a
message id rather than an issue id.
> Make documentation of get-issue-metadata less ambiguous
